'use strict';

/**
 * ServiceHub — Complete Seed Script (Milestones 2C + 2D)
 *
 * Milestone 2C — Identity Foundation:
 *   Roles → Users → UserRoles → UserProfiles → Addresses
 *   → ProviderProfiles → ProviderDocuments
 *
 * Milestone 2D — Service Catalog:
 *   ServiceCategories → Services → ProviderServices
 *   → ProviderAvailability → ProviderTimeOff
 *
 * All accounts use the same password for development convenience:
 *   Password: Password@123
 *
 * Run: npm run seed
 */

const { PrismaClient } = require('@prisma/client');
const bcrypt = require('bcrypt');

const prisma = new PrismaClient({ log: ['warn', 'error'] });

// ─── Password ─────────────────────────────────────────────────────────────────
// Round 10 (vs production 12) keeps seed times fast on dev machines.
const SEED_PASSWORD = 'Password@123';
const HASH_ROUNDS = 10;

// ─── Date helper ──────────────────────────────────────────────────────────────
const daysAgo = (n) => {
  const d = new Date();
  d.setDate(d.getDate() - n);
  d.setHours(0, 0, 0, 0);
  return d;
};

// ─────────────────────────────────────────────────────────────────────────────
// STEP 0 — CLEAR (reverse dependency order, safe to re-run)
// ─────────────────────────────────────────────────────────────────────────────
async function clearFoundationData() {
  // Clear in strict reverse-FK order.
  // Catalog tables (2D) must be cleared BEFORE identity tables (2C) because:
  //   • provider_services FK → provider_profiles (Cascade) AND → services (Restrict)
  //   • services FK → service_categories (Restrict)
  // If we deleted provider_profiles first, provider_services would cascade-delete,
  // but services would still block service_categories deletion.
  // Explicit order prevents any FK violation.

  // ── Support & Disputes tables (2I) ─────────────────────────────────────────
  await prisma.disputeMessage.deleteMany();
  await prisma.dispute.deleteMany();

  // ── Notifications System tables (2H) ───────────────────────────────────────
  await prisma.notification.deleteMany();

  // ── Reviews System tables (2G) ─────────────────────────────────────────────
  await prisma.reviewReply.deleteMany();
  await prisma.review.deleteMany();

  // ── Financial System tables (2F) ───────────────────────────────────────────
  await prisma.payment.deleteMany();
  await prisma.walletTransaction.deleteMany();
  await prisma.wallet.deleteMany();
  await prisma.couponUsage.deleteMany();
  await prisma.coupon.deleteMany();

  // ── Booking System tables (2E) ─────────────────────────────────────────────
  await prisma.bookingStatusHistory.deleteMany();
  await prisma.booking.deleteMany();

  // ── Catalog tables (2D) ────────────────────────────────────────────────────
  await prisma.providerTimeOff.deleteMany();
  await prisma.providerAvailability.deleteMany();
  await prisma.providerService.deleteMany();
  await prisma.service.deleteMany();
  await prisma.serviceCategory.deleteMany();

  // ── Identity tables (2C) ───────────────────────────────────────────────────
  await prisma.providerDocument.deleteMany();
  await prisma.providerProfile.deleteMany();
  await prisma.address.deleteMany();
  await prisma.userProfile.deleteMany();
  await prisma.userRole.deleteMany();
  await prisma.user.deleteMany();
  await prisma.role.deleteMany();
  console.log('  ✓ All seed data cleared (catalog + identity)');
}

// ─────────────────────────────────────────────────────────────────────────────
// STEP 1 — ROLES
// No FK dependencies. Must exist before UserRoles.
// ─────────────────────────────────────────────────────────────────────────────
async function seedRoles() {
  const [adminRole, customerRole, providerRole] = await Promise.all([
    prisma.role.create({ data: { name: 'ADMIN' } }),
    prisma.role.create({ data: { name: 'CUSTOMER' } }),
    prisma.role.create({ data: { name: 'PROVIDER' } }),
  ]);
  console.log('  ✓ 3 Roles created');
  return { adminRole, customerRole, providerRole };
}

// ─────────────────────────────────────────────────────────────────────────────
// STEP 2 — USERS
// No FK dependencies. UUID IDs are generated by Prisma's @default(uuid()).
// ─────────────────────────────────────────────────────────────────────────────
async function seedUsers(hash) {
  // ── Admin ──────────────────────────────────────────────────────────────────
  const admin = await prisma.user.create({
    data: {
      email: 'admin@servicehub.app',
      phone: '+919800000001',
      passwordHash: hash,
      status: 'ACTIVE',
      isVerified: true,
    },
  });

  // ── Customers ──────────────────────────────────────────────────────────────
  const customerData = [
    { email: 'amit.gupta@gmail.com',      phone: '+919811111111', firstName: 'Amit',     lastName: 'Gupta',    dob: new Date('1990-03-15') },
    { email: 'neha.singh@gmail.com',      phone: '+919822222222', firstName: 'Neha',     lastName: 'Singh',    dob: new Date('1993-07-22') },
    { email: 'vikram.malhotra@gmail.com', phone: '+919833333333', firstName: 'Vikram',   lastName: 'Malhotra', dob: new Date('1988-11-05') },
    { email: 'priyanka.reddy@gmail.com',  phone: '+919844444444', firstName: 'Priyanka', lastName: 'Reddy',    dob: new Date('1995-02-18') },
    { email: 'rohit.joshi@gmail.com',     phone: '+919855555555', firstName: 'Rohit',    lastName: 'Joshi',    dob: new Date('1991-09-30') },
    { email: 'kavita.iyer@gmail.com',     phone: '+919866666666', firstName: 'Kavita',   lastName: 'Iyer',     dob: new Date('1987-12-10') },
    { email: 'sameer.khan@gmail.com',     phone: '+919877777777', firstName: 'Sameer',   lastName: 'Khan',     dob: new Date('1992-06-25') },
    { email: 'divya.menon@gmail.com',     phone: '+919888888888', firstName: 'Divya',    lastName: 'Menon',    dob: new Date('1996-04-08') },
  ];

  const customers = [];
  for (const c of customerData) {
    const user = await prisma.user.create({
      data: { email: c.email, phone: c.phone, passwordHash: hash, status: 'ACTIVE', isVerified: true },
    });
    customers.push({ user, ...c });
  }

  // ── Providers ──────────────────────────────────────────────────────────────
  const providerData = [
    { email: 'rajesh.kumar@gmail.com',    phone: '+919900000001', firstName: 'Rajesh',   lastName: 'Kumar' },
    { email: 'suresh.patel@gmail.com',    phone: '+919900000002', firstName: 'Suresh',   lastName: 'Patel' },
    { email: 'anita.sharma@gmail.com',    phone: '+919900000003', firstName: 'Anita',    lastName: 'Sharma' },
    { email: 'mohammed.farouk@gmail.com', phone: '+919900000004', firstName: 'Mohammed', lastName: 'Farouk' },
    { email: 'deepak.verma@gmail.com',    phone: '+919900000005', firstName: 'Deepak',   lastName: 'Verma' },
    { email: 'priya.nair@gmail.com',      phone: '+919900000006', firstName: 'Priya',    lastName: 'Nair' },
  ];

  const providers = [];
  for (const p of providerData) {
    const user = await prisma.user.create({
      data: { email: p.email, phone: p.phone, passwordHash: hash, status: 'ACTIVE', isVerified: true },
    });
    providers.push({ user, ...p });
  }

  console.log(`  ✓ ${1 + customers.length + providers.length} Users created (1 admin, ${customers.length} customers, ${providers.length} providers)`);
  return { admin, customers, providers };
}

// ─────────────────────────────────────────────────────────────────────────────
// STEP 3 — USER ROLES
// Depends on: Users, Roles
// Junction table — enforces @@unique([userId, roleId]) constraint.
// ─────────────────────────────────────────────────────────────────────────────
async function seedUserRoles({ admin, customers, providers }, { adminRole, customerRole, providerRole }) {
  const data = [
    { userId: admin.id, roleId: adminRole.id },
    ...customers.map((c) => ({ userId: c.user.id, roleId: customerRole.id })),
    ...providers.map((p) => ({ userId: p.user.id, roleId: providerRole.id })),
  ];

  // Using createMany — we don't need the returned IDs for this table.
  await prisma.userRole.createMany({ data });
  console.log(`  ✓ ${data.length} UserRoles assigned`);
}

// ─────────────────────────────────────────────────────────────────────────────
// STEP 4 — USER PROFILES
// Depends on: Users (userId FK, @unique — enforces 1:1 at DB level)
// Note: UserProfile has firstName, lastName, avatarUrl, dateOfBirth.
//       There is no gender or bio field in this model per the approved schema.
//       Provider bios are stored in ProviderProfile.bio (Step 6).
// ─────────────────────────────────────────────────────────────────────────────
async function seedUserProfiles({ admin, customers, providers }) {
  const avatar = (fn, ln, bg = '6366f1') =>
    `https://ui-avatars.com/api/?name=${fn}+${ln}&background=${bg}&color=fff&size=256&bold=true`;

  const data = [
    // Admin
    {
      userId: admin.id,
      firstName: 'Aryan',
      lastName: 'Mehta',
      avatarUrl: avatar('Aryan', 'Mehta', '6366f1'),
      dateOfBirth: new Date('1985-06-10'),
    },
    // Customers
    { userId: customers[0].user.id, firstName: 'Amit',     lastName: 'Gupta',    avatarUrl: avatar('Amit',     'Gupta',    'f59e0b'), dateOfBirth: new Date('1990-03-15') },
    { userId: customers[1].user.id, firstName: 'Neha',     lastName: 'Singh',    avatarUrl: avatar('Neha',     'Singh',    'ec4899'), dateOfBirth: new Date('1993-07-22') },
    { userId: customers[2].user.id, firstName: 'Vikram',   lastName: 'Malhotra', avatarUrl: avatar('Vikram',   'Malhotra', '3b82f6'), dateOfBirth: new Date('1988-11-05') },
    { userId: customers[3].user.id, firstName: 'Priyanka', lastName: 'Reddy',    avatarUrl: avatar('Priyanka', 'Reddy',    'a855f7'), dateOfBirth: new Date('1995-02-18') },
    { userId: customers[4].user.id, firstName: 'Rohit',    lastName: 'Joshi',    avatarUrl: avatar('Rohit',    'Joshi',    '10b981'), dateOfBirth: new Date('1991-09-30') },
    { userId: customers[5].user.id, firstName: 'Kavita',   lastName: 'Iyer',     avatarUrl: avatar('Kavita',   'Iyer',     'f43f5e'), dateOfBirth: new Date('1987-12-10') },
    { userId: customers[6].user.id, firstName: 'Sameer',   lastName: 'Khan',     avatarUrl: avatar('Sameer',   'Khan',     '0ea5e9'), dateOfBirth: new Date('1992-06-25') },
    { userId: customers[7].user.id, firstName: 'Divya',    lastName: 'Menon',    avatarUrl: avatar('Divya',    'Menon',    'f97316'), dateOfBirth: new Date('1996-04-08') },
    // Providers
    { userId: providers[0].user.id, firstName: 'Rajesh',   lastName: 'Kumar',    avatarUrl: avatar('Rajesh',   'Kumar',    '64748b'), dateOfBirth: new Date('1982-05-20') },
    { userId: providers[1].user.id, firstName: 'Suresh',   lastName: 'Patel',    avatarUrl: avatar('Suresh',   'Patel',    '64748b'), dateOfBirth: new Date('1984-09-14') },
    { userId: providers[2].user.id, firstName: 'Anita',    lastName: 'Sharma',   avatarUrl: avatar('Anita',    'Sharma',   '64748b'), dateOfBirth: new Date('1989-03-08') },
    { userId: providers[3].user.id, firstName: 'Mohammed', lastName: 'Farouk',   avatarUrl: avatar('Mohammed', 'Farouk',   '64748b'), dateOfBirth: new Date('1986-11-25') },
    { userId: providers[4].user.id, firstName: 'Deepak',   lastName: 'Verma',    avatarUrl: avatar('Deepak',   'Verma',    '64748b'), dateOfBirth: new Date('1978-07-30') },
    { userId: providers[5].user.id, firstName: 'Priya',    lastName: 'Nair',     avatarUrl: avatar('Priya',    'Nair',     '64748b'), dateOfBirth: new Date('1997-01-12') },
  ];

  await prisma.userProfile.createMany({ data });
  console.log(`  ✓ ${data.length} UserProfiles created`);
}

// ─────────────────────────────────────────────────────────────────────────────
// STEP 5 — ADDRESSES
// Depends on: Users (userId FK with CASCADE delete)
// One address per user. Multiple Indian cities represented.
// ─────────────────────────────────────────────────────────────────────────────
async function seedAddresses({ admin, customers, providers }) {
  const data = [
    // ── Admin (Delhi) ────────────────────────────────────────────────────────
    {
      userId: admin.id, label: 'Office', isDefault: true,
      line1: '14, Lodhi Estate', line2: 'Near Lodhi Garden',
      city: 'New Delhi', state: 'Delhi', pincode: '110003',
      latitude: 28.5939, longitude: 77.2273,
    },
    // ── Customers ─────────────────────────────────────────────────────────────
    // Amit Gupta — Ahmedabad
    {
      userId: customers[0].user.id, label: 'Home', isDefault: true,
      line1: '23, Panchvati Society', line2: 'Near Paldi Char Rasta',
      city: 'Ahmedabad', state: 'Gujarat', pincode: '380007',
      latitude: 23.0141, longitude: 72.5558,
    },
    // Neha Singh — Surat
    {
      userId: customers[1].user.id, label: 'Home', isDefault: true,
      line1: '8B, Vesu Residential Area', line2: 'Near Vesu Garden',
      city: 'Surat', state: 'Gujarat', pincode: '395007',
      latitude: 21.1524, longitude: 72.7860,
    },
    // Vikram Malhotra — Mumbai
    {
      userId: customers[2].user.id, label: 'Home', isDefault: true,
      line1: '201, Siddhi Vinayak Towers', line2: 'Andheri West',
      city: 'Mumbai', state: 'Maharashtra', pincode: '400053',
      latitude: 19.1197, longitude: 72.8464,
    },
    // Priyanka Reddy — Bengaluru
    {
      userId: customers[3].user.id, label: 'Home', isDefault: true,
      line1: '45, 12th Main Road', line2: 'Indiranagar, HAL 2nd Stage',
      city: 'Bengaluru', state: 'Karnataka', pincode: '560038',
      latitude: 12.9784, longitude: 77.6408,
    },
    // Rohit Joshi — Pune
    {
      userId: customers[4].user.id, label: 'Home', isDefault: true,
      line1: '12, Sahakarnagar Colony', line2: 'Kothrud',
      city: 'Pune', state: 'Maharashtra', pincode: '411038',
      latitude: 18.5074, longitude: 73.8077,
    },
    // Kavita Iyer — Delhi
    {
      userId: customers[5].user.id, label: 'Home', isDefault: true,
      line1: '7, Pocket B, Sector C', line2: 'Vasant Kunj',
      city: 'New Delhi', state: 'Delhi', pincode: '110070',
      latitude: 28.5244, longitude: 77.1574,
    },
    // Sameer Khan — Vadodara
    {
      userId: customers[6].user.id, label: 'Home', isDefault: true,
      line1: '34, Alkapuri Society', line2: 'Behind Race Course',
      city: 'Vadodara', state: 'Gujarat', pincode: '390007',
      latitude: 22.3119, longitude: 73.1723,
    },
    // Divya Menon — Rajkot
    {
      userId: customers[7].user.id, label: 'Home', isDefault: true,
      line1: '5, Yagnik Road', line2: 'Near Trikon Baug',
      city: 'Rajkot', state: 'Gujarat', pincode: '360001',
      latitude: 22.3039, longitude: 70.8022,
    },
    // ── Providers ─────────────────────────────────────────────────────────────
    // Rajesh Kumar — Ahmedabad
    {
      userId: providers[0].user.id, label: 'Home', isDefault: true,
      line1: '56, Maninagar Cross Roads', line2: 'Near Maninagar Railway Station',
      city: 'Ahmedabad', state: 'Gujarat', pincode: '380008',
      latitude: 22.9906, longitude: 72.6036,
    },
    // Suresh Patel — Surat
    {
      userId: providers[1].user.id, label: 'Home', isDefault: true,
      line1: '12, Aadarsh Society', line2: 'Adajan Patia',
      city: 'Surat', state: 'Gujarat', pincode: '395009',
      latitude: 21.2100, longitude: 72.8211,
    },
    // Anita Sharma — Mumbai
    {
      userId: providers[2].user.id, label: 'Home', isDefault: true,
      line1: '303, Oberoi Complex', line2: 'Goregaon East',
      city: 'Mumbai', state: 'Maharashtra', pincode: '400063',
      latitude: 19.1639, longitude: 72.8563,
    },
    // Mohammed Farouk — Bengaluru
    {
      userId: providers[3].user.id, label: 'Home', isDefault: true,
      line1: '22, EPIP Zone', line2: 'Whitefield Industrial Area',
      city: 'Bengaluru', state: 'Karnataka', pincode: '560066',
      latitude: 12.9698, longitude: 77.7499,
    },
    // Deepak Verma — Pune
    {
      userId: providers[4].user.id, label: 'Home', isDefault: true,
      line1: '8, Magarpatta Road', line2: 'Hadapsar',
      city: 'Pune', state: 'Maharashtra', pincode: '411028',
      latitude: 18.5167, longitude: 73.9326,
    },
    // Priya Nair — Delhi
    {
      userId: providers[5].user.id, label: 'Home', isDefault: true,
      line1: '19, Lajpat Nagar II', line2: 'Central Market Area',
      city: 'New Delhi', state: 'Delhi', pincode: '110024',
      latitude: 28.5672, longitude: 77.2418,
    },
  ];

  await prisma.address.createMany({ data });
  console.log(`  ✓ ${data.length} Addresses created (cities: Ahmedabad, Surat, Mumbai, Bengaluru, Pune, Delhi, Vadodara, Rajkot)`);
}

// ─────────────────────────────────────────────────────────────────────────────
// STEP 6 — PROVIDER PROFILES
// Depends on: Users (userId FK, @unique — enforces 1:1 at DB level)
// Pre-computed stats reflect what the seed's review data will eventually contain.
// Business names are naturally embedded in bios since the schema has no
// dedicated businessName column — bio is the correct field per schema.
// ─────────────────────────────────────────────────────────────────────────────
async function seedProviderProfiles({ providers }) {
  const profileData = [
    // ── [0] Rajesh Kumar — Plumbing & Appliance Repair (Ahmedabad) ───────────
    {
      userId: providers[0].user.id,
      bio: 'Kumar Plumbing Services — Expert plumber and home appliance technician with 8+ years of experience across Ahmedabad. NSDC Level-4 certified. Specializes in pipe repair, bathroom fittings, and all major washing machine brands. 500+ successful service calls. Emergency plumbing available.',
      experienceYears: 8,
      verificationStatus: 'APPROVED',
      avgRating: 4.25,
      totalReviews: 4,
      totalBookings: 4,
      isAvailable: true,
    },
    // ── [1] Suresh Patel — Electrical & AC Repair (Surat) ────────────────────
    {
      userId: providers[1].user.id,
      bio: 'Patel Electricals — Licensed electrical contractor and certified AC technician with 6 years of field experience in Surat. Holds a valid State Electrical Contractor License. Handled 400+ installations. Expert in MCB panels, home wiring, and all major AC brands including Daikin, Voltas, and Blue Star.',
      experienceYears: 6,
      verificationStatus: 'APPROVED',
      avgRating: 4.33,
      totalReviews: 3,
      totalBookings: 3,
      isAvailable: true,
    },
    // ── [2] Anita Sharma — Home Cleaning & Salon Services (Mumbai) ───────────
    {
      userId: providers[2].user.id,
      bio: 'Anita Home Care & Beauty — Professional home cleaning specialist and VLCC-certified beauty therapist based in Mumbai. 4 years of delivering premium cleaning and salon services at doorstep. Uses eco-friendly products for cleaning and high-end brands for beauty treatments. Known for attention to detail.',
      experienceYears: 4,
      verificationStatus: 'APPROVED',
      avgRating: 4.75,
      totalReviews: 4,
      totalBookings: 4,
      isAvailable: true,
    },
    // ── [3] Mohammed Farouk — Pest Control & Cleaning (Bengaluru) ────────────
    {
      userId: providers[3].user.id,
      bio: 'Farouk Pest Solutions — Certified pest control technician serving Bengaluru for 5 years. Uses WHO-approved, eco-friendly formulations that are safe for children and pets. Specializes in cockroach, rodent, mosquito, and general pest management with a 30-day satisfaction guarantee.',
      experienceYears: 5,
      verificationStatus: 'APPROVED',
      avgRating: 3.50,
      totalReviews: 2,
      totalBookings: 2,
      isAvailable: true,
    },
    // ── [4] Deepak Verma — Home Painting (Pune) ──────────────────────────────
    {
      userId: providers[4].user.id,
      bio: 'Verma Painting Works — Senior painting professional with 10 years of experience and 200+ completed projects in Pune. Asian Paints Authorised Painter. Worked with leading construction firms before starting independently. Expertise in interior, exterior, and waterproofing using premium Asian Paints and Berger materials.',
      experienceYears: 10,
      verificationStatus: 'APPROVED',
      avgRating: 5.00,
      totalReviews: 2,
      totalBookings: 2,
      isAvailable: true,
    },
    // ── [5] Priya Nair — Salon at Home (Delhi) — NEW, Under Review ───────────
    {
      userId: providers[5].user.id,
      bio: 'Priya Beauty Studio — Passionate beauty professional trained at Lakme Academy, Mumbai. 2 years of experience providing premium salon services at home in Delhi. Specializes in bridal makeup, advanced skincare, and modern hairstyling. Uses Kiehl\'s, Dermalogica, and L\'Oreal Professional products. Currently undergoing admin verification.',
      experienceYears: 2,
      verificationStatus: 'UNDER_REVIEW',
      avgRating: 0.00,
      totalReviews: 0,
      totalBookings: 0,
      isAvailable: false,
    },
  ];

  // Use individual creates (not createMany) so we can capture IDs for Step 7.
  const profiles = [];
  for (const pd of profileData) {
    const profile = await prisma.providerProfile.create({ data: pd });
    profiles.push(profile);
  }

  console.log(`  ✓ ${profiles.length} ProviderProfiles created`);
  return profiles;
}

// ─────────────────────────────────────────────────────────────────────────────
// STEP 7 — PROVIDER DOCUMENTS
// Depends on: ProviderProfiles (providerId FK with CASCADE delete)
// Every provider has at least one document.
// Mix of APPROVED, PENDING, and REJECTED statuses.
// ─────────────────────────────────────────────────────────────────────────────
async function seedProviderDocuments(providerProfiles) {
  const data = [
    // ── [0] Rajesh Kumar — APPROVED (all 3 documents cleared) ────────────────
    {
      providerId: providerProfiles[0].id,
      documentType: 'ID_PROOF',
      documentUrl: 'https://cdn.servicehub.app/docs/rajesh/aadhar_card.jpg',
      status: 'APPROVED',
      adminNotes: 'Aadhar card verified. Name and photo match registration.',
      reviewedAt: daysAgo(60),
    },
    {
      providerId: providerProfiles[0].id,
      documentType: 'ADDRESS_PROOF',
      documentUrl: 'https://cdn.servicehub.app/docs/rajesh/electricity_bill.jpg',
      status: 'APPROVED',
      adminNotes: 'Electricity bill verified. Address matches profile.',
      reviewedAt: daysAgo(59),
    },
    {
      providerId: providerProfiles[0].id,
      documentType: 'CERTIFICATION',
      documentUrl: 'https://cdn.servicehub.app/docs/rajesh/nsdc_plumbing_cert.pdf',
      status: 'APPROVED',
      adminNotes: 'NSDC Level-4 Plumbing & Pipe Fitting certificate verified. Valid.',
      reviewedAt: daysAgo(58),
    },
    // ── [1] Suresh Patel — APPROVED (all 3 cleared) ───────────────────────────
    {
      providerId: providerProfiles[1].id,
      documentType: 'ID_PROOF',
      documentUrl: 'https://cdn.servicehub.app/docs/suresh/aadhar_card.jpg',
      status: 'APPROVED',
      adminNotes: 'Aadhar card verified. Clear scan with all details visible.',
      reviewedAt: daysAgo(90),
    },
    {
      providerId: providerProfiles[1].id,
      documentType: 'ADDRESS_PROOF',
      documentUrl: 'https://cdn.servicehub.app/docs/suresh/bank_statement.pdf',
      status: 'APPROVED',
      adminNotes: 'Bank statement verified. Address and name match registration.',
      reviewedAt: daysAgo(89),
    },
    {
      providerId: providerProfiles[1].id,
      documentType: 'CERTIFICATION',
      documentUrl: 'https://cdn.servicehub.app/docs/suresh/electrical_contractor_license.pdf',
      status: 'APPROVED',
      adminNotes: 'Gujarat State Electrical Contractor License verified. License No. GJ-EC-2019-0284. Valid until 2027.',
      reviewedAt: daysAgo(87),
    },
    // ── [2] Anita Sharma — APPROVED (ID + Address), no certification needed ───
    {
      providerId: providerProfiles[2].id,
      documentType: 'ID_PROOF',
      documentUrl: 'https://cdn.servicehub.app/docs/anita/aadhar_card.jpg',
      status: 'APPROVED',
      adminNotes: 'Aadhar card verified successfully.',
      reviewedAt: daysAgo(120),
    },
    {
      providerId: providerProfiles[2].id,
      documentType: 'ADDRESS_PROOF',
      documentUrl: 'https://cdn.servicehub.app/docs/anita/rental_agreement.pdf',
      status: 'APPROVED',
      adminNotes: 'Notarized rental agreement verified. Address confirmed.',
      reviewedAt: daysAgo(118),
    },
    {
      providerId: providerProfiles[2].id,
      documentType: 'CERTIFICATION',
      documentUrl: 'https://cdn.servicehub.app/docs/anita/vlcc_certificate.pdf',
      status: 'APPROVED',
      adminNotes: 'VLCC Institute beauty therapy certificate verified. Authentic.',
      reviewedAt: daysAgo(116),
    },
    // ── [3] Mohammed Farouk — ID APPROVED, Address PENDING ───────────────────
    {
      providerId: providerProfiles[3].id,
      documentType: 'ID_PROOF',
      documentUrl: 'https://cdn.servicehub.app/docs/farouk/aadhar_card.jpg',
      status: 'APPROVED',
      adminNotes: 'Aadhar card verified. Clear and complete.',
      reviewedAt: daysAgo(100),
    },
    {
      providerId: providerProfiles[3].id,
      documentType: 'ADDRESS_PROOF',
      documentUrl: 'https://cdn.servicehub.app/docs/farouk/utility_bill.jpg',
      status: 'PENDING',
      adminNotes: 'Document received. Awaiting review — in queue.',
      reviewedAt: null,
    },
    {
      providerId: providerProfiles[3].id,
      documentType: 'CERTIFICATION',
      documentUrl: 'https://cdn.servicehub.app/docs/farouk/pest_control_license.pdf',
      status: 'APPROVED',
      adminNotes: 'Karnataka State Pest Control Operator License. Valid.',
      reviewedAt: daysAgo(95),
    },
    // ── [4] Deepak Verma — All APPROVED ───────────────────────────────────────
    {
      providerId: providerProfiles[4].id,
      documentType: 'ID_PROOF',
      documentUrl: 'https://cdn.servicehub.app/docs/deepak/pan_card.jpg',
      status: 'APPROVED',
      adminNotes: 'PAN card verified. Name matches registration exactly.',
      reviewedAt: daysAgo(150),
    },
    {
      providerId: providerProfiles[4].id,
      documentType: 'ADDRESS_PROOF',
      documentUrl: 'https://cdn.servicehub.app/docs/deepak/voter_id.jpg',
      status: 'APPROVED',
      adminNotes: 'Voter ID verified. Address matches profile registration.',
      reviewedAt: daysAgo(148),
    },
    {
      providerId: providerProfiles[4].id,
      documentType: 'CERTIFICATION',
      documentUrl: 'https://cdn.servicehub.app/docs/deepak/asian_paints_cert.pdf',
      status: 'APPROVED',
      adminNotes: 'Asian Paints Authorised Painter & Contractor Certificate. Cert No. AP-PUNE-2347.',
      reviewedAt: daysAgo(145),
    },
    // ── [5] Priya Nair — Mixed: PENDING, PENDING, REJECTED (new provider) ─────
    {
      providerId: providerProfiles[5].id,
      documentType: 'ID_PROOF',
      documentUrl: 'https://cdn.servicehub.app/docs/priya/aadhar_card.jpg',
      status: 'PENDING',
      adminNotes: 'Received. Awaiting verification — in review queue.',
      reviewedAt: null,
    },
    {
      providerId: providerProfiles[5].id,
      documentType: 'ADDRESS_PROOF',
      documentUrl: 'https://cdn.servicehub.app/docs/priya/address_proof_v1.jpg',
      status: 'REJECTED',
      adminNotes: 'Document rejected: Image is blurry and address text is not legible. Please re-upload a clear, high-resolution scan.',
      reviewedAt: daysAgo(3),
    },
    {
      providerId: providerProfiles[5].id,
      documentType: 'CERTIFICATION',
      documentUrl: 'https://cdn.servicehub.app/docs/priya/lakme_certificate.pdf',
      status: 'PENDING',
      adminNotes: 'Lakme Academy certificate received. Verifying authenticity with institution.',
      reviewedAt: null,
    },
  ];

  await prisma.providerDocument.createMany({ data });

  // Summarise the document status mix for the log
  const approved = data.filter((d) => d.status === 'APPROVED').length;
  const pending  = data.filter((d) => d.status === 'PENDING').length;
  const rejected = data.filter((d) => d.status === 'REJECTED').length;

  console.log(`  ✓ ${data.length} ProviderDocuments created (${approved} APPROVED, ${pending} PENDING, ${rejected} REJECTED)`);
}

// ═════════════════════════════════════════════════════════════════════════════
// MILESTONE 2D — SERVICE CATALOG
// ═════════════════════════════════════════════════════════════════════════════

// ─────────────────────────────────────────────────────────────────────────────
// STEP 8 — SERVICE CATEGORIES
// No FK dependencies. Must exist before Services.
// sortOrder drives UI display sequence.
// ─────────────────────────────────────────────────────────────────────────────
async function seedServiceCategories() {
  const data = [
    {
      name: 'Plumbing',
      description: 'Expert plumbing solutions for leaks, fittings, drain cleaning, and full bathroom work.',
      iconUrl: 'https://cdn.servicehub.app/icons/plumbing.svg',
      isActive: true,
      sortOrder: 1,
    },
    {
      name: 'Electrical',
      description: 'Certified electricians for fan installation, wiring, switchboard repair, and inverter servicing.',
      iconUrl: 'https://cdn.servicehub.app/icons/electrical.svg',
      isActive: true,
      sortOrder: 2,
    },
    {
      name: 'Cleaning',
      description: 'Professional deep cleaning for homes, kitchens, bathrooms, and upholstery.',
      iconUrl: 'https://cdn.servicehub.app/icons/cleaning.svg',
      isActive: true,
      sortOrder: 3,
    },
    {
      name: 'AC Repair',
      description: 'AC servicing, gas refill, installation, and uninstallation for all major brands.',
      iconUrl: 'https://cdn.servicehub.app/icons/ac.svg',
      isActive: true,
      sortOrder: 4,
    },
    {
      name: 'Appliance Repair',
      description: 'Doorstep repair for washing machines, refrigerators, microwaves, and geysers.',
      iconUrl: 'https://cdn.servicehub.app/icons/appliance.svg',
      isActive: true,
      sortOrder: 5,
    },
    {
      name: 'Home Painting',
      description: 'Premium interior and exterior painting, waterproofing, and designer finishes.',
      iconUrl: 'https://cdn.servicehub.app/icons/painting.svg',
      isActive: true,
      sortOrder: 6,
    },
    {
      name: 'Salon at Home',
      description: 'Professional beauty and grooming services delivered at your doorstep.',
      iconUrl: 'https://cdn.servicehub.app/icons/salon.svg',
      isActive: true,
      sortOrder: 7,
    },
    {
      name: 'Pest Control',
      description: 'Safe and certified pest control treatments for cockroaches, rodents, mosquitoes, and more.',
      iconUrl: 'https://cdn.servicehub.app/icons/pest.svg',
      isActive: true,
      sortOrder: 8,
    },
  ];

  const categories = [];
  for (const cat of data) {
    categories.push(await prisma.serviceCategory.create({ data: cat }));
  }
  console.log(`  ✓ ${categories.length} ServiceCategories created`);
  // Index: [0]=Plumbing [1]=Electrical [2]=Cleaning [3]=AC [4]=Appliance [5]=Painting [6]=Salon [7]=Pest
  return categories;
}

// ─────────────────────────────────────────────────────────────────────────────
// STEP 9 — SERVICES (32 total, 4 per category)
// FK → service_categories.id (Restrict)
// Duration is embedded in description (schema has no dedicated duration field).
// ─────────────────────────────────────────────────────────────────────────────
async function seedServices(cats) {
  // cats[0]=Plumbing, [1]=Electrical, [2]=Cleaning, [3]=AC,
  // [4]=Appliance, [5]=Painting, [6]=Salon, [7]=Pest
  const serviceData = [
    // ── PLUMBING (idx 0–3) ────────────────────────────────────────────────────
    {
      categoryId: cats[0].id,
      name: 'Pipe Leak Repair',
      description: 'Expert diagnosis and repair of all pipe leak types — concealed, overhead, or underground. Avg. duration: 45–90 min.',
      basePrice: 499,
      unit: 'per visit',
      imageUrl: 'https://cdn.servicehub.app/services/pipe-leak.jpg',
      isActive: true,
    },
    {
      categoryId: cats[0].id,
      name: 'Tap & Faucet Installation',
      description: 'Installation and replacement of all tap and faucet types including mixers and kitchen sinks. Avg. duration: 30–60 min per tap.',
      basePrice: 399,
      unit: 'per tap',
      imageUrl: 'https://cdn.servicehub.app/services/tap-install.jpg',
      isActive: true,
    },
    {
      categoryId: cats[0].id,
      name: 'Drain Unclogging',
      description: 'High-pressure drain cleaning for kitchen, bathroom, and floor drains. Clears grease, hair, and debris. Avg. duration: 30–45 min.',
      basePrice: 349,
      unit: 'per drain',
      imageUrl: 'https://cdn.servicehub.app/services/drain.jpg',
      isActive: true,
    },
    {
      categoryId: cats[0].id,
      name: 'Bathroom Fitting',
      description: 'Complete bathroom fitting — EWC, wash basin, shower unit, and accessories installation. Avg. duration: 2–4 hours.',
      basePrice: 1499,
      unit: 'per bathroom',
      imageUrl: 'https://cdn.servicehub.app/services/bathroom.jpg',
      isActive: true,
    },
    // ── ELECTRICAL (idx 4–7) ──────────────────────────────────────────────────
    {
      categoryId: cats[1].id,
      name: 'Ceiling Fan Installation',
      description: 'Safe installation of ceiling fans including BLDC fans, with earthing check and speed regulator fitting. Avg. duration: 45–75 min.',
      basePrice: 399,
      unit: 'per fan',
      imageUrl: 'https://cdn.servicehub.app/services/fan-install.jpg',
      isActive: true,
    },
    {
      categoryId: cats[1].id,
      name: 'Switchboard Repair & Replacement',
      description: 'Repair or full replacement of switchboards, modular sockets, MCBs, and ELCB units. Avg. duration: 30–60 min.',
      basePrice: 299,
      unit: 'per switchboard',
      imageUrl: 'https://cdn.servicehub.app/services/switchboard.jpg',
      isActive: true,
    },
    {
      categoryId: cats[1].id,
      name: 'Light Fixture Installation',
      description: 'Installation of LED panels, chandeliers, strip lights, and all decorative fixtures. Avg. duration: 30–60 min per fixture.',
      basePrice: 499,
      unit: 'per fixture',
      imageUrl: 'https://cdn.servicehub.app/services/light.jpg',
      isActive: true,
    },
    {
      categoryId: cats[1].id,
      name: 'Inverter & UPS Repair',
      description: 'Diagnosis and repair for all inverter and UPS brands — Luminous, Microtek, Exide, Su-Kam. Avg. duration: 1–2 hours.',
      basePrice: 699,
      unit: 'per unit',
      imageUrl: 'https://cdn.servicehub.app/services/inverter.jpg',
      isActive: true,
    },
    // ── CLEANING (idx 8–11) ───────────────────────────────────────────────────
    {
      categoryId: cats[2].id,
      name: 'Full Home Deep Cleaning',
      description: 'Comprehensive deep clean of entire home — floors, walls, kitchen, bathrooms, balconies. Eco-friendly products. Avg. duration: 4–6 hours.',
      basePrice: 1999,
      unit: 'per home (2BHK)',
      imageUrl: 'https://cdn.servicehub.app/services/deep-clean.jpg',
      isActive: true,
    },
    {
      categoryId: cats[2].id,
      name: 'Kitchen Deep Cleaning',
      description: 'Thorough kitchen cleaning — chimney, hob, cabinets, tiles, countertop, sink, and all appliances. Avg. duration: 2–3 hours.',
      basePrice: 999,
      unit: 'per kitchen',
      imageUrl: 'https://cdn.servicehub.app/services/kitchen-clean.jpg',
      isActive: true,
    },
    {
      categoryId: cats[2].id,
      name: 'Bathroom Cleaning',
      description: 'Deep bathroom sanitization — tiles, grout, fixtures, commode, and shower area. Hospital-grade disinfectants. Avg. duration: 45–90 min.',
      basePrice: 599,
      unit: 'per bathroom',
      imageUrl: 'https://cdn.servicehub.app/services/bathroom-clean.jpg',
      isActive: true,
    },
    {
      categoryId: cats[2].id,
      name: 'Sofa & Upholstery Cleaning',
      description: 'Dry steam and shampoo cleaning for fabric sofas, chairs, cushions, and curtains. Avg. duration: 1.5–2.5 hours.',
      basePrice: 799,
      unit: 'per 3-seater',
      imageUrl: 'https://cdn.servicehub.app/services/sofa-clean.jpg',
      isActive: true,
    },
    // ── AC REPAIR (idx 12–15) ─────────────────────────────────────────────────
    {
      categoryId: cats[3].id,
      name: 'AC Service & Cleaning',
      description: 'Complete AC service — indoor/outdoor coil cleaning, filter wash, drain check, and performance test. Avg. duration: 1–1.5 hours.',
      basePrice: 699,
      unit: 'per unit',
      imageUrl: 'https://cdn.servicehub.app/services/ac-service.jpg',
      isActive: true,
    },
    {
      categoryId: cats[3].id,
      name: 'AC Gas Refill',
      description: 'Refrigerant gas top-up (R22, R32, R410A) with leak detection and post-refill performance test. Avg. duration: 1.5–2 hours.',
      basePrice: 1800,
      unit: 'per unit',
      imageUrl: 'https://cdn.servicehub.app/services/ac-gas.jpg',
      isActive: true,
    },
    {
      categoryId: cats[3].id,
      name: 'AC Installation',
      description: 'Professional split AC installation — wall brackets, copper piping, electrical connections, and trial run. Avg. duration: 2–3 hours.',
      basePrice: 1299,
      unit: 'per unit',
      imageUrl: 'https://cdn.servicehub.app/services/ac-install.jpg',
      isActive: true,
    },
    {
      categoryId: cats[3].id,
      name: 'AC Uninstallation & Shifting',
      description: 'Safe AC uninstallation with gas recovery and packing for safe transport. Avg. duration: 1–1.5 hours.',
      basePrice: 599,
      unit: 'per unit',
      imageUrl: 'https://cdn.servicehub.app/services/ac-uninstall.jpg',
      isActive: true,
    },
    // ── APPLIANCE REPAIR (idx 16–19) ──────────────────────────────────────────
    {
      categoryId: cats[4].id,
      name: 'Washing Machine Repair',
      description: 'Diagnosis and repair for front load, top load, and semi-automatic machines. All brands covered. Avg. duration: 1–2 hours.',
      basePrice: 499,
      unit: 'per visit',
      imageUrl: 'https://cdn.servicehub.app/services/washing-machine.jpg',
      isActive: true,
    },
    {
      categoryId: cats[4].id,
      name: 'Refrigerator Repair',
      description: 'Repair for all refrigerator issues — cooling failure, compressor, gas, thermostat. Single and double-door. Avg. duration: 1–2 hours.',
      basePrice: 599,
      unit: 'per visit',
      imageUrl: 'https://cdn.servicehub.app/services/fridge.jpg',
      isActive: true,
    },
    {
      categoryId: cats[4].id,
      name: 'Microwave Oven Repair',
      description: 'Repair of solo, grill, and convection microwave ovens. Turntable, magnetron, door switch issues. Avg. duration: 45–90 min.',
      basePrice: 399,
      unit: 'per visit',
      imageUrl: 'https://cdn.servicehub.app/services/microwave.jpg',
      isActive: true,
    },
    {
      categoryId: cats[4].id,
      name: 'Geyser Repair & Service',
      description: 'Repair and servicing of electric and gas geysers. Thermostat, heating element, and safety valve replacement. Avg. duration: 45–75 min.',
      basePrice: 449,
      unit: 'per visit',
      imageUrl: 'https://cdn.servicehub.app/services/geyser.jpg',
      isActive: true,
    },
    // ── HOME PAINTING (idx 20–23) ─────────────────────────────────────────────
    {
      categoryId: cats[5].id,
      name: 'Interior Wall Painting',
      description: 'Premium interior painting — wall putty, primer, and 2 top-coat finish. Asian Paints / Berger materials. Avg. duration: 1–2 days per room.',
      basePrice: 3499,
      unit: 'per room',
      imageUrl: 'https://cdn.servicehub.app/services/interior-paint.jpg',
      isActive: true,
    },
    {
      categoryId: cats[5].id,
      name: 'Exterior Painting',
      description: 'Weather-resistant exterior painting with UV-proof primer and 2-coat finish. Avg. duration: 1–2 days per 100 sqft.',
      basePrice: 1299,
      unit: 'per 100 sqft',
      imageUrl: 'https://cdn.servicehub.app/services/exterior-paint.jpg',
      isActive: true,
    },
    {
      categoryId: cats[5].id,
      name: 'Waterproofing Treatment',
      description: 'Terrace, bathroom, and wall waterproofing using Dr. Fixit SilverFoil or Sika systems. 5-year effectiveness. Avg. duration: 1 day.',
      basePrice: 1999,
      unit: 'per treatment',
      imageUrl: 'https://cdn.servicehub.app/services/waterproof.jpg',
      isActive: true,
    },
    {
      categoryId: cats[5].id,
      name: 'Texture & Designer Painting',
      description: 'Decorative texture finishes — sand, Venetian plaster, metallic, and stencil patterns. Avg. duration: 1–2 days per room.',
      basePrice: 2499,
      unit: 'per room',
      imageUrl: 'https://cdn.servicehub.app/services/texture-paint.jpg',
      isActive: true,
    },
    // ── SALON AT HOME (idx 24–27) ─────────────────────────────────────────────
    {
      categoryId: cats[6].id,
      name: 'Haircut & Styling',
      description: 'Professional haircut, wash, conditioning, and blow-dry by a certified stylist. All hair types. Avg. duration: 45–75 min.',
      basePrice: 399,
      unit: 'per session',
      imageUrl: 'https://cdn.servicehub.app/services/haircut.jpg',
      isActive: true,
    },
    {
      categoryId: cats[6].id,
      name: 'Facial & Skin Cleanup',
      description: 'Deep pore cleansing facial — steam, scrub, extraction, mask, and moisturiser. Premium products. Avg. duration: 60–90 min.',
      basePrice: 699,
      unit: 'per session',
      imageUrl: 'https://cdn.servicehub.app/services/facial.jpg',
      isActive: true,
    },
    {
      categoryId: cats[6].id,
      name: 'Waxing & Threading',
      description: 'Full or partial waxing (Rica/chocolate wax) and eyebrow/upper-lip threading. Hygienic disposable tools. Avg. duration: 45–75 min.',
      basePrice: 349,
      unit: 'per session',
      imageUrl: 'https://cdn.servicehub.app/services/waxing.jpg',
      isActive: true,
    },
    {
      categoryId: cats[6].id,
      name: 'Bridal Makeup & Grooming',
      description: 'Complete bridal package — HD/airbrush foundation, contouring, eye makeup, and finishing. Trial session included. Avg. duration: 3–4 hours.',
      basePrice: 5999,
      unit: 'per session',
      imageUrl: 'https://cdn.servicehub.app/services/bridal.jpg',
      isActive: true,
    },
    // ── PEST CONTROL (idx 28–31) ──────────────────────────────────────────────
    {
      categoryId: cats[7].id,
      name: 'Cockroach Control Treatment',
      description: 'Gel bait + residual spray for complete cockroach elimination. Child and pet safe. 30-day guarantee. Avg. duration: 45–60 min.',
      basePrice: 999,
      unit: 'per home (2BHK)',
      imageUrl: 'https://cdn.servicehub.app/services/cockroach.jpg',
      isActive: true,
    },
    {
      categoryId: cats[7].id,
      name: 'Rodent & Rat Control',
      description: 'Mechanical traps, bait stations, and entry-point sealing for comprehensive rodent control. Avg. duration: 1–1.5 hours.',
      basePrice: 1499,
      unit: 'per treatment',
      imageUrl: 'https://cdn.servicehub.app/services/rodent.jpg',
      isActive: true,
    },
    {
      categoryId: cats[7].id,
      name: 'Mosquito Control Spray',
      description: 'Larvicide and residual spray targeting breeding grounds. WHO-approved chemicals. 30-day effectiveness. Avg. duration: 45–60 min.',
      basePrice: 1199,
      unit: 'per home',
      imageUrl: 'https://cdn.servicehub.app/services/mosquito.jpg',
      isActive: true,
    },
    {
      categoryId: cats[7].id,
      name: 'General Pest Control',
      description: 'Comprehensive treatment for ants, spiders, silverfish, centipedes, and 15+ common household pests. Avg. duration: 1–1.5 hours.',
      basePrice: 1799,
      unit: 'per home (2BHK)',
      imageUrl: 'https://cdn.servicehub.app/services/pest-general.jpg',
      isActive: true,
    },
  ];

  const services = [];
  for (const svc of serviceData) {
    services.push(await prisma.service.create({ data: svc }));
  }
  console.log(`  ✓ ${services.length} Services created across 8 categories (4 per category)`);
  return services;
  // idx: 0-3=Plumbing, 4-7=Electrical, 8-11=Cleaning, 12-15=AC,
  //      16-19=Appliance, 20-23=Painting, 24-27=Salon, 28-31=Pest
}

// ─────────────────────────────────────────────────────────────────────────────
// STEP 10 — PROVIDER SERVICES
// FK → provider_profiles.id (Cascade) + services.id (Restrict)
// Custom prices vary ±10–25% from base price — realistic market variation.
// APPROVED providers: isAvailable = true
// UNDER_REVIEW providers (Priya): isAvailable = false
// ─────────────────────────────────────────────────────────────────────────────
async function seedProviderServices(pp, svcs) {
  // pp[0]=Rajesh, pp[1]=Suresh, pp[2]=Anita, pp[3]=Farouk, pp[4]=Deepak, pp[5]=Priya
  // svcs[0-3]=Plumbing, [4-7]=Electrical, [8-11]=Cleaning, [12-15]=AC,
  //       [16-19]=Appliance, [20-23]=Painting, [24-27]=Salon, [28-31]=Pest

  const allProviderServices = [
    // ── Rajesh Kumar [0] — Plumbing + Appliance Repair (7 services) ───────────
    { providerId: pp[0].id, serviceId: svcs[0].id,  customPrice: 449, isAvailable: true,  description: '8+ yrs experience. Emergency callout within 2 hrs. ISI-marked materials.' },
    { providerId: pp[0].id, serviceId: svcs[1].id,  customPrice: 349, isAvailable: true,  description: 'All brands. Concealed and wall-mounted fittings. Genuine parts only.' },
    { providerId: pp[0].id, serviceId: svcs[2].id,  customPrice: 299, isAvailable: true,  description: 'High-pressure jetting available for severe blockages.' },
    { providerId: pp[0].id, serviceId: svcs[3].id,  customPrice: 1349, isAvailable: true, description: 'Full bathroom renovation packages also available on quote.' },
    { providerId: pp[0].id, serviceId: svcs[16].id, customPrice: 449, isAvailable: true,  description: 'LG, Samsung, Whirlpool, IFB specialist. Front & top load.' },
    { providerId: pp[0].id, serviceId: svcs[17].id, customPrice: 549, isAvailable: true,  description: 'All brands including double-door and side-by-side models.' },
    { providerId: pp[0].id, serviceId: svcs[19].id, customPrice: 399, isAvailable: true,  description: 'Electric and gas geysers. Safety valve inspection included.' },

    // ── Suresh Patel [1] — Electrical + AC Repair (8 services) ───────────────
    { providerId: pp[1].id, serviceId: svcs[4].id,  customPrice: 349, isAvailable: true,  description: 'Standard and BLDC fans. Earthing and balance check included.' },
    { providerId: pp[1].id, serviceId: svcs[5].id,  customPrice: 269, isAvailable: true,  description: 'Modular and conventional boards. MCB replacement included.' },
    { providerId: pp[1].id, serviceId: svcs[6].id,  customPrice: 449, isAvailable: true,  description: 'LED, decorative, and architectural lighting. Concealed wiring.' },
    { providerId: pp[1].id, serviceId: svcs[7].id,  customPrice: 649, isAvailable: true,  description: 'Luminous, Microtek, Exide, Su-Kam. Battery check included.' },
    { providerId: pp[1].id, serviceId: svcs[12].id, customPrice: 649, isAvailable: true,  description: 'Certified for Daikin, Voltas, Blue Star, LG, Samsung, Hitachi.' },
    { providerId: pp[1].id, serviceId: svcs[13].id, customPrice: 1699, isAvailable: true, description: 'R22 and R32 gas. Leak test and pressure check included.' },
    { providerId: pp[1].id, serviceId: svcs[14].id, customPrice: 1199, isAvailable: true, description: 'Split AC only. Copper piping up to 3 m included.' },
    { providerId: pp[1].id, serviceId: svcs[15].id, customPrice: 549, isAvailable: true,  description: 'Gas recovery and safe packaging for transport.' },

    // ── Anita Sharma [2] — Cleaning + Salon (7 services) ─────────────────────
    { providerId: pp[2].id, serviceId: svcs[8].id,  customPrice: 1799, isAvailable: true, description: 'Team of 2. Eco-friendly products. 3BHK at ₹2799 on request.' },
    { providerId: pp[2].id, serviceId: svcs[9].id,  customPrice: 899,  isAvailable: true, description: 'Includes chimney cleaning, cabinet interior, and tile grout.' },
    { providerId: pp[2].id, serviceId: svcs[10].id, customPrice: 549,  isAvailable: true, description: 'Hospital-grade disinfectants. Sanitary ware descaling.' },
    { providerId: pp[2].id, serviceId: svcs[11].id, customPrice: 749,  isAvailable: true, description: 'Dry steam cleaning for all fabric types. No water damage.' },
    { providerId: pp[2].id, serviceId: svcs[24].id, customPrice: 369,  isAvailable: true, description: 'VLCC trained. All hair types. Includes wash and blow-dry.' },
    { providerId: pp[2].id, serviceId: svcs[25].id, customPrice: 649,  isAvailable: true, description: 'Lotus Herbals and Kaya products. Sensitive skin specialist.' },
    { providerId: pp[2].id, serviceId: svcs[26].id, customPrice: 299,  isAvailable: true, description: 'Rica and chocolate wax. Hygienic disposable tools only.' },

    // ── Mohammed Farouk [3] — Pest Control + Cleaning (6 services) ───────────
    { providerId: pp[3].id, serviceId: svcs[28].id, customPrice: 899,  isAvailable: true, description: 'Gel bait method. No odor. 30-day re-treatment guarantee.' },
    { providerId: pp[3].id, serviceId: svcs[29].id, customPrice: 1349, isAvailable: true, description: 'Bait stations + mechanical traps + all entry points sealed.' },
    { providerId: pp[3].id, serviceId: svcs[30].id, customPrice: 1099, isAvailable: true, description: 'Larvicide spray targeting stagnant water sources. WHO-approved.' },
    { providerId: pp[3].id, serviceId: svcs[31].id, customPrice: 1649, isAvailable: true, description: 'Covers 15+ pest species. Annual contract at 20% discount.' },
    { providerId: pp[3].id, serviceId: svcs[10].id, customPrice: 499,  isAvailable: true, description: 'Bathroom deep clean with pest-deterrent disinfection spray.' },
    { providerId: pp[3].id, serviceId: svcs[9].id,  customPrice: 849,  isAvailable: true, description: 'Kitchen cleaning with cockroach-repellent gel along edges.' },

    // ── Deepak Verma [4] — Home Painting (4 services) ────────────────────────
    { providerId: pp[4].id, serviceId: svcs[20].id, customPrice: 3199, isAvailable: true, description: 'Asian Paints Royale/Royale Aspira. Putty and primer included.' },
    { providerId: pp[4].id, serviceId: svcs[21].id, customPrice: 1199, isAvailable: true, description: 'Apex Ultima Protek. UV, rain, and fungus resistant.' },
    { providerId: pp[4].id, serviceId: svcs[22].id, customPrice: 1799, isAvailable: true, description: 'Dr. Fixit SilverFoil. 5-year manufacturer backed guarantee.' },
    { providerId: pp[4].id, serviceId: svcs[23].id, customPrice: 2299, isAvailable: true, description: 'Sand, Venetian plaster, and metallic finishes. Sample shown before start.' },

    // ── Priya Nair [5] — Salon (4 services, UNDER_REVIEW → all unavailable) ──
    { providerId: pp[5].id, serviceId: svcs[24].id, customPrice: 349, isAvailable: false, description: 'Lakme Academy trained. Keratin and smoothening specialist.' },
    { providerId: pp[5].id, serviceId: svcs[25].id, customPrice: 599, isAvailable: false, description: 'Dermalogica and Kiehl\'s products. Anti-ageing specialist.' },
    { providerId: pp[5].id, serviceId: svcs[26].id, customPrice: 299, isAvailable: false, description: 'Rica and chocolate wax. Sensitive skin-safe formula.' },
    { providerId: pp[5].id, serviceId: svcs[27].id, customPrice: 5499, isAvailable: false, description: 'Full bridal package. HD + airbrush. Trial session included.' },
  ];

  await prisma.providerService.createMany({ data: allProviderServices });

  const perProvider = [
    { name: 'Rajesh Kumar',    count: 7 },
    { name: 'Suresh Patel',    count: 8 },
    { name: 'Anita Sharma',    count: 7 },
    { name: 'Mohammed Farouk', count: 6 },
    { name: 'Deepak Verma',    count: 4 },
    { name: 'Priya Nair',      count: 4, note: '(all unavailable — under review)' },
  ];
  perProvider.forEach((p) =>
    console.log(`     ${p.name}: ${p.count} services ${p.note || ''}`)
  );
  console.log(`  ✓ ${allProviderServices.length} ProviderServices created`);
}

// ─────────────────────────────────────────────────────────────────────────────
// STEP 11 — PROVIDER AVAILABILITY
// FK → provider_profiles.id (Cascade)
// @@unique([providerId, dayOfWeek]) — one schedule row per provider per day.
// ─────────────────────────────────────────────────────────────────────────────
async function seedProviderAvailability(pp) {
  const ALL   = ['MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY','SUNDAY'];
  const MON_SAT = ALL.slice(0, 6); // Monday–Saturday
  const TUE_SUN = ALL.slice(1);    // Tuesday–Sunday
  const MON_FRI = ALL.slice(0, 5); // Monday–Friday

  const schedules = [
    // Rajesh [0]: Mon–Sat 08:00–18:00  (Sunday rest — observes family day)
    { pId: pp[0].id, days: MON_SAT, start: '08:00', end: '18:00' },
    // Suresh [1]: Mon–Sun 09:00–17:00  (works all 7 days, ends early)
    { pId: pp[1].id, days: ALL,     start: '09:00', end: '17:00' },
    // Anita [2]: Tue–Sun 09:00–19:00   (Monday off — admin and restocking day)
    { pId: pp[2].id, days: TUE_SUN, start: '09:00', end: '19:00' },
    // Farouk [3]: Mon–Sat 07:30–16:30  (early start for pest chemical effectiveness)
    { pId: pp[3].id, days: MON_SAT, start: '07:30', end: '16:30' },
    // Deepak [4]: Mon–Fri 08:00–17:00  (weekends off — painting projects are weekday)
    { pId: pp[4].id, days: MON_FRI, start: '08:00', end: '17:00' },
    // Priya [5]: Mon–Sun 10:00–20:00   (evening slots for working professionals)
    { pId: pp[5].id, days: ALL,     start: '10:00', end: '20:00' },
  ];

  const rows = [];
  for (const sch of schedules) {
    for (const day of sch.days) {
      rows.push({ providerId: sch.pId, dayOfWeek: day, startTime: sch.start, endTime: sch.end, isAvailable: true });
    }
  }

  await prisma.providerAvailability.createMany({ data: rows });
  console.log(`  ✓ ${rows.length} ProviderAvailability slots created`);
  console.log('     Rajesh: Mon–Sat 08:00–18:00  |  Suresh: Mon–Sun 09:00–17:00');
  console.log('     Anita:  Tue–Sun 09:00–19:00  |  Farouk: Mon–Sat 07:30–16:30');
  console.log('     Deepak: Mon–Fri 08:00–17:00  |  Priya:  Mon–Sun 10:00–20:00');
}

// ─────────────────────────────────────────────────────────────────────────────
// STEP 12 — PROVIDER TIME OFF
// FK → provider_profiles.id (Cascade)
// All dates are in the future (from seed run date) so they appear in
// availability queries as upcoming blocked slots.
// ─────────────────────────────────────────────────────────────────────────────
async function seedProviderTimeOff(pp) {
  const data = [
    // ── Rajesh Kumar [0] ──────────────────────────────────────────────────────
    {
      providerId: pp[0].id,
      startDate:  new Date('2026-08-13'),
      endDate:    new Date('2026-08-17'),
      reason:     'Independence Day family vacation — trip to Manali',
    },
    {
      providerId: pp[0].id,
      startDate:  new Date('2026-10-20'),
      endDate:    new Date('2026-10-24'),
      reason:     'Diwali holiday — travelling home to Rajkot',
    },
    // ── Suresh Patel [1] ──────────────────────────────────────────────────────
    {
      providerId: pp[1].id,
      startDate:  new Date('2026-08-22'),
      endDate:    new Date('2026-08-24'),
      reason:     'Sister\'s wedding function in Ahmedabad',
    },
    {
      providerId: pp[1].id,
      startDate:  new Date('2026-09-05'),
      endDate:    new Date('2026-09-05'),
      reason:     'Janmashtami — local festival holiday',
    },
    // ── Anita Sharma [2] ──────────────────────────────────────────────────────
    {
      providerId: pp[2].id,
      startDate:  new Date('2026-08-28'),
      endDate:    new Date('2026-08-30'),
      reason:     'Routine medical checkup and recovery leave',
    },
    {
      providerId: pp[2].id,
      startDate:  new Date('2026-10-02'),
      endDate:    new Date('2026-10-02'),
      reason:     'Gandhi Jayanti — national holiday',
    },
    // ── Mohammed Farouk [3] ───────────────────────────────────────────────────
    {
      providerId: pp[3].id,
      startDate:  new Date('2026-08-10'),
      endDate:    new Date('2026-08-11'),
      reason:     'Muharram — religious observance',
    },
    {
      providerId: pp[3].id,
      startDate:  new Date('2026-09-15'),
      endDate:    new Date('2026-09-17'),
      reason:     'Annual pest control technician recertification training — Bengaluru',
    },
    // ── Deepak Verma [4] ──────────────────────────────────────────────────────
    {
      providerId: pp[4].id,
      startDate:  new Date('2026-09-12'),
      endDate:    new Date('2026-09-14'),
      reason:     'Asian Paints contractor certification renewal — Pune workshop',
    },
    {
      providerId: pp[4].id,
      startDate:  new Date('2026-10-13'),
      endDate:    new Date('2026-10-15'),
      reason:     'Navratri family holiday',
    },
    // ── Priya Nair [5] ────────────────────────────────────────────────────────
    {
      providerId: pp[5].id,
      startDate:  new Date('2026-08-07'),
      endDate:    new Date('2026-08-09'),
      reason:     'Beauty India Expo 2026 — attending as delegate, Mumbai',
    },
    {
      providerId: pp[5].id,
      startDate:  new Date('2026-09-20'),
      endDate:    new Date('2026-09-21'),
      reason:     'Onam family celebration — travelling to Kerala',
    },
  ];

  await prisma.providerTimeOff.createMany({ data });
  console.log(`  ✓ ${data.length} ProviderTimeOff records created (2 per provider)`);
}

// ─────────────────────────────────────────────────────────────────────────────
// MAIN — Orchestrator
// ─────────────────────────────────────────────────────────────────────────────
async function main() {
  console.log('\n╔══════════════════════════════════════════════╗');
  console.log('║   ServiceHub — Complete Seed (2C - 2I)       ║');
  console.log('╚══════════════════════════════════════════════╝\n');
  console.log('🔑  All accounts password: Password@123\n');

  const passwordHash = await bcrypt.hash(SEED_PASSWORD, HASH_ROUNDS);

  // ── Step 0: Clear ──────────────────────────────────────────────────────────
  console.log('[ Step 0 ] Clearing all seed data...');
  await clearFoundationData();

  // ── Step 1: Roles ──────────────────────────────────────────────────────────
  console.log('[ Step 1 ] Seeding Roles...');
  const roles = await seedRoles();

  // ── Step 2: Users ──────────────────────────────────────────────────────────
  console.log('[ Step 2 ] Seeding Users...');
  const { admin, customers, providers } = await seedUsers(passwordHash);

  // ── Step 3: User Roles ─────────────────────────────────────────────────────
  console.log('[ Step 3 ] Assigning User Roles...');
  await seedUserRoles({ admin, customers, providers }, roles);

  // ── Step 4: User Profiles ──────────────────────────────────────────────────
  console.log('[ Step 4 ] Seeding User Profiles...');
  await seedUserProfiles({ admin, customers, providers });

  // ── Step 5: Addresses ──────────────────────────────────────────────────────
  console.log('[ Step 5 ] Seeding Addresses...');
  await seedAddresses({ admin, customers, providers });

  // ── Step 6: Provider Profiles ──────────────────────────────────────────────
  console.log('[ Step 6 ] Seeding Provider Profiles...');
  const providerProfiles = await seedProviderProfiles({ providers });

  // ── Step 7: Provider Documents ─────────────────────────────────────────────
  console.log('[ Step 7 ] Seeding Provider Documents...');
  await seedProviderDocuments(providerProfiles);

  // ── Step 8: Service Categories ─────────────────────────────────────────────
  console.log('[ Step 8 ] Seeding Service Categories...');
  const categories = await seedServiceCategories();

  // ── Step 9: Services ───────────────────────────────────────────────────────
  console.log('[ Step 9 ] Seeding Services...');
  const services = await seedServices(categories);

  // ── Step 10: Provider Services ─────────────────────────────────────────────
  console.log('[ Step 10 ] Seeding Provider Services...');
  await seedProviderServices(providerProfiles, services);

  // ── Step 11: Provider Availability ────────────────────────────────────────
  console.log('[ Step 11 ] Seeding Provider Availability...');
  await seedProviderAvailability(providerProfiles);

  // ── Step 12: Provider Time Off ─────────────────────────────────────────────
  console.log('[ Step 12 ] Seeding Provider Time Off...');
  await seedProviderTimeOff(providerProfiles);

  // ── Step 13: Bookings ──────────────────────────────────────────────────────
  console.log('[ Step 13 ] Seeding Bookings...');
  await seedBookings();

  // ── Step 14: Financial System ──────────────────────────────────────────────
  console.log('[ Step 14 ] Seeding Financial System...');
  await seedFinancials();

  // ── Step 15: Reviews & Replies ─────────────────────────────────────────────
  console.log('[ Step 15 ] Seeding Reviews and Replies...');
  await seedReviews();

  // ── Step 16: Notifications ─────────────────────────────────────────────────
  console.log('[ Step 16 ] Seeding Notifications...');
  await seedNotifications();

  // ── Step 17: Support & Disputes ────────────────────────────────────────────
  console.log('[ Step 17 ] Seeding Support & Disputes...');
  await seedSupportAndDisputes();

  // ── Summary ────────────────────────────────────────────────────────────────
  console.log('\n╔══════════════════════════════════════════════╗');
  console.log('║   ✅  Full seed complete! (2C - 2I)           ║');
  console.log('╚══════════════════════════════════════════════╝\n');
  console.log('📋 Quick reference:\n');
  console.log('  👤 Admin:    admin@servicehub.app');
  console.log('  🧑 Customers: 8 accounts (amit.gupta → divya.menon @gmail.com)');
  console.log('  🔧 Providers: 6 accounts (rajesh.kumar → priya.nair @gmail.com)');
  console.log('  📂 Categories: 8  |  🛠  Services: 32  |  🔗 ProviderServices: 36');
  console.log('  📅 Availability slots: 38  |  🚫 Time-off records: 12');
  console.log('  📅 Bookings: 38 (Past, Present, Future)');
  console.log('  💰 Financials: 15 Wallets | 7 Coupons | Payments + Retries');
  console.log('  ⭐ Reviews: Simulated customer reviews and provider replies');
  console.log('  🔔 Notifications: Multi-event system + promotional alerts');
  console.log('  ⚖️ Support: Simulated disputes and message threads');
  console.log('\n  All passwords: Password@123\n');
}

// ─────────────────────────────────────────────────────────────────────────────
// STEP 13 — BOOKINGS
// ─────────────────────────────────────────────────────────────────────────────
async function seedBookings() {
  const customers = await prisma.user.findMany({
    where: { userRoles: { some: { role: { name: 'CUSTOMER' } } } },
    include: { addresses: true },
    orderBy: { email: 'asc' }
  });

  const providers = await prisma.user.findMany({
    where: { userRoles: { some: { role: { name: 'PROVIDER' } } } },
    include: {
      providerProfile: {
        include: {
          providerServices: true
        }
      }
    },
    orderBy: { email: 'asc' }
  });

  const getCust = (emailPrefix) => customers.find(c => c.email.startsWith(emailPrefix));
  const getProv = (emailPrefix) => providers.find(p => p.email.startsWith(emailPrefix));

  const cAmit = getCust('amit');
  const cNeha = getCust('neha');
  const cVikram = getCust('vikram');
  const cPriyanka = getCust('priyanka');
  const cRohit = getCust('rohit');
  const cKavita = getCust('kavita');
  const cSameer = getCust('sameer');
  const cDivya = getCust('divya');

  const pRajesh = getProv('rajesh');
  const pSuresh = getProv('suresh');
  const pAnita = getProv('anita');
  const pFarouk = getProv('mohammed');
  const pDeepak = getProv('deepak');

  const addBooking = async ({ cust, prov, pSvcIdx, status, daysOffset, hr }) => {
    const pProfile = prov.providerProfile;
    const pSvc = pProfile.providerServices[pSvcIdx];
    
    if (!pSvc) throw new Error(`Invalid pSvcIdx ${pSvcIdx} for provider ${prov.email}`);

    const scheduledAt = new Date();
    scheduledAt.setDate(scheduledAt.getDate() + daysOffset);
    scheduledAt.setHours(hr, 0, 0, 0);

    const createdAt = new Date(scheduledAt);
    createdAt.setDate(createdAt.getDate() - 2); 

    let completedAt = null;
    if (status === 'COMPLETED') {
      completedAt = new Date(scheduledAt);
      completedAt.setHours(completedAt.getHours() + 2);
    }

    let cancellationReason = null;
    if (status === 'CANCELLED') {
      cancellationReason = "Change of plans";
    }

    const booking = await prisma.booking.create({
      data: {
        customerId: cust.id,
        providerId: pProfile.id,
        serviceId: pSvc.serviceId,
        providerServiceId: pSvc.id,
        addressId: cust.addresses[0].id,
        status: status,
        scheduledAt: scheduledAt,
        completedAt: completedAt,
        baseAmount: pSvc.customPrice,
        discountAmount: 0.00,
        totalAmount: pSvc.customPrice,
        notes: "Please call upon arrival",
        cancellationReason: cancellationReason,
        createdAt: createdAt,
        updatedAt: completedAt || scheduledAt, 
      }
    });

    const histories = [];
    let hDate = new Date(createdAt);

    histories.push({
      bookingId: booking.id,
      status: 'PENDING',
      changedById: cust.id,
      reason: 'Booking requested by customer',
      createdAt: new Date(hDate)
    });

    if (status !== 'PENDING') {
      hDate = new Date(hDate);
      hDate.setHours(hDate.getHours() + 2);
      
      const cancelledBeforeConfirm = status === 'CANCELLED' && Math.random() > 0.5;
      
      if (!cancelledBeforeConfirm) {
        histories.push({
          bookingId: booking.id,
          status: 'CONFIRMED',
          changedById: prov.id,
          reason: 'Provider confirmed the booking',
          createdAt: new Date(hDate)
        });
      }

      if (status === 'IN_PROGRESS' || status === 'COMPLETED') {
        hDate = new Date(scheduledAt);
        histories.push({
          bookingId: booking.id,
          status: 'IN_PROGRESS',
          changedById: prov.id,
          reason: 'Provider started the job',
          createdAt: new Date(hDate)
        });
      }

      if (status === 'COMPLETED') {
        hDate = new Date(completedAt);
        histories.push({
          bookingId: booking.id,
          status: 'COMPLETED',
          changedById: prov.id,
          reason: 'Job completed successfully',
          createdAt: new Date(hDate)
        });
      }

      if (status === 'CANCELLED') {
        hDate = new Date(scheduledAt);
        hDate.setDate(hDate.getDate() - 1);
        histories.push({
          bookingId: booking.id,
          status: 'CANCELLED',
          changedById: cust.id,
          reason: cancellationReason,
          createdAt: new Date(hDate)
        });
      }
    }

    await prisma.bookingStatusHistory.createMany({ data: histories });
    return booking;
  };

  const configs = [
    { cust: cAmit, prov: pRajesh, pSvcIdx: 0, status: 'COMPLETED', daysOffset: -10, hr: 10 },
    { cust: cNeha, prov: pSuresh, pSvcIdx: 1, status: 'COMPLETED', daysOffset: -8, hr: 14 },
    { cust: cVikram, prov: pAnita, pSvcIdx: 0, status: 'COMPLETED', daysOffset: -12, hr: 9 },
    { cust: cPriyanka, prov: pFarouk, pSvcIdx: 2, status: 'COMPLETED', daysOffset: -15, hr: 11 },
    { cust: cRohit, prov: pDeepak, pSvcIdx: 1, status: 'COMPLETED', daysOffset: -5, hr: 10 },
    { cust: cKavita, prov: pRajesh, pSvcIdx: 2, status: 'COMPLETED', daysOffset: -20, hr: 16 },
    { cust: cSameer, prov: pSuresh, pSvcIdx: 3, status: 'COMPLETED', daysOffset: -2, hr: 13 },
    { cust: cDivya, prov: pAnita, pSvcIdx: 1, status: 'COMPLETED', daysOffset: -25, hr: 15 },
    { cust: cAmit, prov: pFarouk, pSvcIdx: 0, status: 'COMPLETED', daysOffset: -7, hr: 8 },
    { cust: cNeha, prov: pRajesh, pSvcIdx: 3, status: 'COMPLETED', daysOffset: -18, hr: 12 },
    { cust: cVikram, prov: pDeepak, pSvcIdx: 0, status: 'COMPLETED', daysOffset: -30, hr: 9 },
    { cust: cPriyanka, prov: pSuresh, pSvcIdx: 4, status: 'COMPLETED', daysOffset: -11, hr: 11 },
    { cust: cRohit, prov: pAnita, pSvcIdx: 3, status: 'COMPLETED', daysOffset: -14, hr: 14 },
    { cust: cKavita, prov: pFarouk, pSvcIdx: 1, status: 'COMPLETED', daysOffset: -9, hr: 10 },
    { cust: cSameer, prov: pRajesh, pSvcIdx: 1, status: 'COMPLETED', daysOffset: -3, hr: 15 },

    { cust: cDivya, prov: pSuresh, pSvcIdx: 2, status: 'CONFIRMED', daysOffset: 2, hr: 10 },
    { cust: cAmit, prov: pAnita, pSvcIdx: 2, status: 'CONFIRMED', daysOffset: 5, hr: 11 },
    { cust: cNeha, prov: pFarouk, pSvcIdx: 3, status: 'CONFIRMED', daysOffset: 3, hr: 9 },
    { cust: cVikram, prov: pRajesh, pSvcIdx: 4, status: 'CONFIRMED', daysOffset: 7, hr: 14 },
    { cust: cPriyanka, prov: pDeepak, pSvcIdx: 2, status: 'CONFIRMED', daysOffset: 4, hr: 10 },
    { cust: cRohit, prov: pSuresh, pSvcIdx: 5, status: 'CONFIRMED', daysOffset: 6, hr: 13 },
    { cust: cKavita, prov: pAnita, pSvcIdx: 4, status: 'CONFIRMED', daysOffset: 1, hr: 15 },
    { cust: cSameer, prov: pFarouk, pSvcIdx: 2, status: 'CONFIRMED', daysOffset: 8, hr: 8 },
    { cust: cDivya, prov: pRajesh, pSvcIdx: 5, status: 'CONFIRMED', daysOffset: 2, hr: 16 },
    { cust: cAmit, prov: pDeepak, pSvcIdx: 3, status: 'CONFIRMED', daysOffset: 9, hr: 9 },

    { cust: cNeha, prov: pAnita, pSvcIdx: 5, status: 'PENDING', daysOffset: 4, hr: 10 },
    { cust: cVikram, prov: pSuresh, pSvcIdx: 6, status: 'PENDING', daysOffset: 2, hr: 11 },
    { cust: cPriyanka, prov: pRajesh, pSvcIdx: 6, status: 'PENDING', daysOffset: 5, hr: 14 },
    { cust: cRohit, prov: pFarouk, pSvcIdx: 4, status: 'PENDING', daysOffset: 3, hr: 12 },
    { cust: cKavita, prov: pDeepak, pSvcIdx: 1, status: 'PENDING', daysOffset: 6, hr: 9 },

    { cust: cSameer, prov: pAnita, pSvcIdx: 6, status: 'IN_PROGRESS', daysOffset: 0, hr: 10 },
    { cust: cDivya, prov: pSuresh, pSvcIdx: 7, status: 'IN_PROGRESS', daysOffset: 0, hr: 11 },
    { cust: cAmit, prov: pRajesh, pSvcIdx: 2, status: 'IN_PROGRESS', daysOffset: 0, hr: 9 },

    { cust: cNeha, prov: pFarouk, pSvcIdx: 5, status: 'CANCELLED', daysOffset: -5, hr: 10 },
    { cust: cVikram, prov: pDeepak, pSvcIdx: 2, status: 'CANCELLED', daysOffset: -2, hr: 14 },
    { cust: cPriyanka, prov: pAnita, pSvcIdx: 2, status: 'CANCELLED', daysOffset: 4, hr: 11 },
    { cust: cRohit, prov: pSuresh, pSvcIdx: 1, status: 'CANCELLED', daysOffset: 6, hr: 15 },
    { cust: cKavita, prov: pRajesh, pSvcIdx: 4, status: 'CANCELLED', daysOffset: -10, hr: 9 },
  ];

  for (const c of configs) {
     await addBooking(c);
  }
  
  console.log('  ✓ 38 Bookings created with status history');
}

// ─────────────────────────────────────────────────────────────────────────────
// STEP 14 — FINANCIAL SYSTEM
// ─────────────────────────────────────────────────────────────────────────────
async function seedFinancials() {
  const users = await prisma.user.findMany({ include: { userRoles: { include: { role: true } } } });
  
  // 1. Wallets
  const walletsData = users.map(u => ({
    userId: u.id,
    balance: 0,
  }));
  await prisma.wallet.createMany({ data: walletsData });
  const wallets = await prisma.wallet.findMany();
  
  const processTx = async (userId, type, amount, status, desc, bookingId = null) => {
    return await prisma.$transaction(async (tx) => {
      const wallet = await tx.wallet.findUnique({ where: { userId } });
      const amountDec = parseFloat(amount);
      
      let before = parseFloat(wallet.balance);
      let after = before;
      if (status === 'COMPLETED') {
          if (type === 'CREDIT') after = before + amountDec;
          if (type === 'DEBIT') after = before - amountDec;
      }

      const wtx = await tx.walletTransaction.create({
        data: {
          walletId: wallet.id,
          type: type,
          amount: amountDec,
          status: status,
          description: desc,
          bookingId: bookingId,
          balanceBefore: before,
          balanceAfter: after
        }
      });

      if (status === 'COMPLETED') {
        await tx.wallet.update({
          where: { id: wallet.id },
          data: { balance: after }
        });
      }
      return wtx;
    });
  };

  // Initial balance top-up
  for (const u of users) {
    const isCustomer = u.userRoles.some(r => r.role.name === 'CUSTOMER');
    const isProvider = u.userRoles.some(r => r.role.name === 'PROVIDER');
    
    let topUp = 0;
    if (isCustomer) topUp = 5000 + Math.floor(Math.random() * 5000);
    if (isProvider) topUp = 1000 + Math.floor(Math.random() * 2000);

    if (topUp > 0) {
      await processTx(u.id, 'CREDIT', topUp, 'COMPLETED', 'Initial Wallet Top-up');
    }
  }

  // 2. Coupons
  const couponsData = [
    { code: 'FIRST50', type: 'FLAT', discountValue: 50.00, minOrderValue: 200.00, status: 'ACTIVE', maxUsage: 100, perUserLimit: 1, validFrom: new Date(new Date().setFullYear(new Date().getFullYear()-1)), validUntil: new Date(new Date().setFullYear(new Date().getFullYear()+1)) },
    { code: 'WELCOME10', type: 'PERCENTAGE', discountValue: 10.00, maxDiscount: 150.00, minOrderValue: 500.00, status: 'ACTIVE', maxUsage: 50, perUserLimit: 1, validFrom: new Date(new Date().setFullYear(new Date().getFullYear()-1)), validUntil: new Date(new Date().setFullYear(new Date().getFullYear()+1)) },
    { code: 'SAVE100', type: 'FLAT', discountValue: 100.00, minOrderValue: 1000.00, status: 'ACTIVE', maxUsage: 200, perUserLimit: 2, validFrom: new Date(new Date().setMonth(new Date().getMonth()-1)), validUntil: new Date(new Date().setMonth(new Date().getMonth()+1)) },
    { code: 'FESTIVE20', type: 'PERCENTAGE', discountValue: 20.00, maxDiscount: 300.00, minOrderValue: 800.00, status: 'ACTIVE', maxUsage: 100, perUserLimit: 1, validFrom: new Date(new Date().setMonth(new Date().getMonth()-2)), validUntil: new Date(new Date().setMonth(new Date().getMonth()+2)) },
    { code: 'MONSOON15', type: 'PERCENTAGE', discountValue: 15.00, maxDiscount: 200.00, minOrderValue: 400.00, status: 'EXPIRED', maxUsage: 500, perUserLimit: 3, validFrom: new Date(new Date().setFullYear(new Date().getFullYear()-2)), validUntil: new Date(new Date().setFullYear(new Date().getFullYear()-1)) },
    { code: 'HOMECARE25', type: 'FLAT', discountValue: 250.00, minOrderValue: 1500.00, status: 'ACTIVE', maxUsage: 20, perUserLimit: 1, validFrom: new Date(), validUntil: new Date(new Date().setFullYear(new Date().getFullYear()+1)) },
    { code: 'TESTCOUPON', type: 'FLAT', discountValue: 500.00, minOrderValue: 500.00, status: 'INACTIVE', maxUsage: 10, perUserLimit: 1, validFrom: new Date(), validUntil: new Date(new Date().setFullYear(new Date().getFullYear()+1)) }
  ];
  await prisma.coupon.createMany({ data: couponsData });
  const coupons = await prisma.coupon.findMany();

  // 3. Process Bookings (Payments, Coupon Usage, Wallet tx)
  const bookings = await prisma.booking.findMany({ include: { provider: true }, orderBy: { id: 'asc' } });

  let pIdCounter = 1000;
  let retryCount = 0;
  let couponUsageCount = 0;
  let paymentCount = 0;
  let platformRevenue = 0;
  let providerEarnings = 0;
  let totalRefunds = 0;
  
  for (const b of bookings) {
    let finalAmount = parseFloat(b.baseAmount);
    let discount = 0;
    
    // Attempt coupon (only active, 30% chance)
    if (Math.random() < 0.3) {
      const activeCoupons = coupons.filter(c => c.status === 'ACTIVE' && parseFloat(c.minOrderValue) <= finalAmount);
      if (activeCoupons.length > 0) {
        const coupon = activeCoupons[Math.floor(Math.random() * activeCoupons.length)];
        
        if (coupon.type === 'FLAT') {
          discount = parseFloat(coupon.discountValue);
        } else {
          discount = (finalAmount * parseFloat(coupon.discountValue)) / 100;
          if (coupon.maxDiscount && discount > parseFloat(coupon.maxDiscount)) {
            discount = parseFloat(coupon.maxDiscount);
          }
        }
        
        finalAmount -= discount;
        
        await prisma.booking.update({
          where: { id: b.id },
          data: { couponId: coupon.id, discountAmount: discount, totalAmount: finalAmount }
        });
        
        await prisma.couponUsage.create({
          data: {
            couponId: coupon.id,
            userId: b.customerId,
            bookingId: b.id,
            usedAt: b.createdAt
          }
        });
        
        await prisma.coupon.update({
          where: { id: coupon.id },
          data: { usageCount: { increment: 1 } }
        });
        couponUsageCount++;
      }
    }

    // Payment Logic
    const isWallet = Math.random() < 0.4;
    const method = isWallet ? 'WALLET' : (Math.random() < 0.5 ? 'CARD' : 'UPI');
    const bDate = b.createdAt;
    
    let isRetry = false;
    if (b.status === 'COMPLETED' && retryCount < 3) {
       isRetry = true;
       retryCount++;
    }

    if (isRetry) {
       await prisma.payment.create({
         data: { bookingId: b.id, transactionRef: `TXN-F1-${pIdCounter++}`, amount: finalAmount, method, status: 'FAILED', createdAt: bDate, updatedAt: bDate, gatewayResponse: { code: 'E101', msg: 'Insufficient funds' } }
       });
       await prisma.payment.create({
         data: { bookingId: b.id, transactionRef: `TXN-F2-${pIdCounter++}`, amount: finalAmount, method, status: 'FAILED', createdAt: new Date(bDate.getTime() + 1000*60*5), updatedAt: new Date(bDate.getTime() + 1000*60*5), gatewayResponse: { code: 'E102', msg: 'Timeout' } }
       });
       paymentCount += 2;
    }

    let paymentStatus = 'PENDING';
    if (b.status === 'COMPLETED' || b.status === 'IN_PROGRESS' || b.status === 'CONFIRMED') {
      paymentStatus = 'SUCCESS';
    } else if (b.status === 'CANCELLED') {
      paymentStatus = Math.random() < 0.5 ? 'REFUNDED' : 'FAILED';
    }
    
    const paidAt = paymentStatus === 'SUCCESS' ? new Date(bDate.getTime() + 1000*60*10) : null;
    
    await prisma.payment.create({
       data: { 
         bookingId: b.id, 
         transactionRef: `TXN-${paymentStatus}-${pIdCounter++}`, 
         amount: finalAmount, 
         method, 
         status: paymentStatus, 
         createdAt: bDate, 
         updatedAt: paidAt || bDate, 
         paidAt,
         gatewayResponse: { msg: `Payment ${paymentStatus}` }
       }
    });
    paymentCount++;

    // Wallet deductions for Customers
    if (paymentStatus === 'SUCCESS' || paymentStatus === 'REFUNDED') {
       if (method === 'WALLET') {
         await processTx(b.customerId, 'DEBIT', finalAmount, 'COMPLETED', `Payment for booking #${b.id}`, b.id);
       }
    }

    // Provider earnings (For simplicity, provider gets paid when COMPLETED)
    if (b.status === 'COMPLETED') {
       const fee = finalAmount * 0.10; // 10% platform fee
       const pEarnings = finalAmount - fee;
       platformRevenue += fee;
       providerEarnings += pEarnings;
       
       await processTx(b.provider.userId, 'CREDIT', pEarnings, 'COMPLETED', `Earnings for booking #${b.id}`, b.id);
    }
    
    // Refund logic
    if (paymentStatus === 'REFUNDED') {
       totalRefunds += finalAmount;
       if (method === 'WALLET') {
         await processTx(b.customerId, 'CREDIT', finalAmount, 'COMPLETED', `Refund for cancelled booking #${b.id}`, b.id);
       }
    }
  }

  const wCount = await prisma.wallet.count();
  const txCount = await prisma.walletTransaction.count();
  console.log(`  ✓ ${wCount} Wallets created, ${txCount} Wallet Transactions processed`);
  console.log(`  ✓ ${paymentCount} Payments created (${retryCount} retries simulated)`);
  console.log(`  ✓ ${coupons.length} Coupons created, ${couponUsageCount} Usages`);
}

// ─────────────────────────────────────────────────────────────────────────────
// STEP 15 — REVIEWS SYSTEM
// ─────────────────────────────────────────────────────────────────────────────
async function seedReviews() {
  const completedBookings = await prisma.booking.findMany({
    where: { status: 'COMPLETED' },
    include: { provider: true }
  });

  // We want ~10-12 reviews out of 15 completed bookings. 
  // We'll shuffle and pick 12.
  const shuffled = completedBookings.sort(() => 0.5 - Math.random());
  const selectedBookings = shuffled.slice(0, 12);

  const reviewComments = [
    { rating: 5, comment: "Excellent service. Very professional." },
    { rating: 5, comment: "Arrived on time and finished quickly. Highly recommended." },
    { rating: 5, comment: "Very professional technician, knew exactly what to do." },
    { rating: 5, comment: "Fantastic experience! The problem was fixed in no time." },
    { rating: 5, comment: "Satisfied with the overall experience." },
    { rating: 4, comment: "Good work but arrived slightly late. Otherwise great." },
    { rating: 4, comment: "Service was good, but the price could be a little better." },
    { rating: 4, comment: "Very polite and helpful. Solved the issue." },
    { rating: 4, comment: "Would definitely book again." },
    { rating: 3, comment: "The issue was fixed, but it took much longer than expected." },
    { rating: 3, comment: "Average experience. The professional was okay but left a bit of a mess." }
  ];

  const replyComments = [
    "Thank you for your valuable feedback. We're glad you liked the service!",
    "We appreciate your review. Hoping to serve you again.",
    "Sorry about the delay. We'll improve next time.",
    "Thank you for choosing us!",
    "We're glad you had a good experience. Let us know if you need any further assistance."
  ];

  let reviewCount = 0;
  let replyCount = 0;

  for (const b of selectedBookings) {
    // Pick a random review template based on probabilities
    const rand = Math.random();
    let template;
    if (rand < 0.6) {
      template = reviewComments.filter(r => r.rating === 5)[Math.floor(Math.random() * 5)];
    } else if (rand < 0.9) {
      template = reviewComments.filter(r => r.rating === 4)[Math.floor(Math.random() * 4)];
    } else {
      template = reviewComments.filter(r => r.rating === 3)[Math.floor(Math.random() * 2)];
    }

    const reviewDate = new Date(b.completedAt.getTime() + 1000 * 60 * 60 * 24); // 1 day after completion

    const review = await prisma.review.create({
      data: {
        bookingId: b.id,
        customerId: b.customerId,
        providerId: b.providerId,
        rating: template.rating,
        comment: template.comment,
        createdAt: reviewDate,
        updatedAt: reviewDate
      }
    });
    reviewCount++;

    // 50% chance of reply
    if (Math.random() < 0.5) {
      const replyTemplate = replyComments[Math.floor(Math.random() * replyComments.length)];
      const replyDate = new Date(reviewDate.getTime() + 1000 * 60 * 60 * 5); // 5 hours after review

      await prisma.reviewReply.create({
        data: {
          reviewId: review.id,
          providerId: b.providerId,
          comment: replyTemplate,
          createdAt: replyDate,
          updatedAt: replyDate
        }
      });
      replyCount++;
    }
  }

  // Update Provider ratings
  const providers = await prisma.providerProfile.findMany();
  for (const p of providers) {
    const reviews = await prisma.review.findMany({ where: { providerId: p.id } });
    if (reviews.length > 0) {
      const totalRatings = reviews.reduce((sum, r) => sum + r.rating, 0);
      const avgRating = totalRatings / reviews.length;
      await prisma.providerProfile.update({
        where: { id: p.id },
        data: {
          totalReviews: reviews.length,
          avgRating: parseFloat(avgRating.toFixed(2))
        }
      });
    }
  }

  console.log(`  ✓ ${reviewCount} Reviews generated for completed bookings`);
  console.log(`  ✓ ${replyCount} Replies generated by providers`);
}

// ─────────────────────────────────────────────────────────────────────────────
// STEP 16 — NOTIFICATIONS SYSTEM
// ─────────────────────────────────────────────────────────────────────────────
async function seedNotifications() {
  const users = await prisma.user.findMany({ include: { userRoles: { include: { role: true } } } });
  const bookings = await prisma.booking.findMany({ include: { payments: true, review: true, provider: true } });
  
  const notificationsData = [];
  
  // 1. System Welcome (All users)
  for (const u of users) {
    notificationsData.push({
      userId: u.id,
      type: 'SYSTEM',
      title: 'Welcome to ServiceHub!',
      body: 'Thank you for joining our platform. We are excited to have you!',
      isRead: true,
      createdAt: u.createdAt,
      data: { action: 'welcome' }
    });
  }
  
  // 2. Promotional (Random subset of customers)
  const customers = users.filter(u => u.userRoles.some(r => r.role.name === 'CUSTOMER'));
  for (const c of customers) {
    if (Math.random() > 0.3) {
      const pDate = new Date(c.createdAt.getTime() + 1000 * 60 * 60 * 24 * 5); // 5 days after join
      notificationsData.push({
        userId: c.id,
        type: 'PROMOTIONAL',
        title: 'Special Discount Inside!',
        body: 'Use code FIRST50 to get ₹50 off your next home service booking.',
        isRead: Math.random() > 0.4,
        createdAt: pDate,
        data: { couponCode: 'FIRST50' }
      });
    }
  }

  // 3. Booking & Payment Events
  for (const b of bookings) {
    const pDate = b.createdAt;
    
    // Customer: Booking Created
    notificationsData.push({
      userId: b.customerId,
      type: 'BOOKING_UPDATE',
      title: 'Booking Requested',
      body: `Your booking #${b.id} has been received and is pending provider confirmation.`,
      isRead: true,
      createdAt: pDate,
      data: { bookingId: b.id }
    });
    
    // Provider: New Request
    notificationsData.push({
      userId: b.provider.userId,
      type: 'BOOKING_UPDATE',
      title: 'New Booking Request',
      body: `You have a new booking request #${b.id}. Please confirm your availability.`,
      isRead: true,
      createdAt: pDate,
      data: { bookingId: b.id }
    });

    if (b.status !== 'PENDING') {
      const confDate = new Date(pDate.getTime() + 1000 * 60 * 60 * 2);
      
      // Customer: Confirmed
      if (b.status === 'CONFIRMED' || b.status === 'IN_PROGRESS' || b.status === 'COMPLETED') {
        notificationsData.push({
          userId: b.customerId,
          type: 'BOOKING_UPDATE',
          title: 'Booking Confirmed!',
          body: `Your booking #${b.id} has been confirmed by the provider.`,
          isRead: Math.random() > 0.2,
          createdAt: confDate,
          data: { bookingId: b.id }
        });
      }
      
      if (b.status === 'CANCELLED') {
        notificationsData.push({
          userId: b.provider.userId,
          type: 'BOOKING_UPDATE',
          title: 'Booking Cancelled',
          body: `Booking #${b.id} has been cancelled by the customer.`,
          isRead: Math.random() > 0.1,
          createdAt: new Date(b.scheduledAt.getTime() - 1000 * 60 * 60 * 24),
          data: { bookingId: b.id }
        });
      }
      
      if (b.status === 'COMPLETED') {
        const compDate = b.completedAt || new Date(b.scheduledAt.getTime() + 1000 * 60 * 60 * 2);
        // Customer: Rate your service
        notificationsData.push({
          userId: b.customerId,
          type: 'REVIEW_REQUEST',
          title: 'How was your service?',
          body: `Your booking #${b.id} is complete. Please leave a review!`,
          isRead: Math.random() > 0.3,
          createdAt: new Date(compDate.getTime() + 1000 * 60 * 30), // 30 mins later
          data: { bookingId: b.id }
        });
      }
    }
    
    // Payments
    for (const p of b.payments) {
      const payType = 'PAYMENT';
      
      if (p.status === 'SUCCESS') {
        notificationsData.push({
          userId: b.customerId,
          type: payType,
          title: 'Payment Successful',
          body: `Your payment of ₹${p.amount} for booking #${b.id} was successful.`,
          isRead: Math.random() > 0.1,
          createdAt: p.updatedAt,
          data: { paymentId: p.id, bookingId: b.id }
        });
        notificationsData.push({
          userId: b.provider.userId,
          type: payType,
          title: 'Payment Received',
          body: `Payment received for booking #${b.id}.`,
          isRead: Math.random() > 0.1,
          createdAt: p.updatedAt,
          data: { paymentId: p.id, bookingId: b.id }
        });
      } else if (p.status === 'FAILED') {
        notificationsData.push({
          userId: b.customerId,
          type: payType,
          title: 'Payment Failed',
          body: `Your payment attempt for booking #${b.id} failed. Please try again.`,
          isRead: Math.random() > 0.05,
          createdAt: p.updatedAt,
          data: { paymentId: p.id, bookingId: b.id }
        });
      } else if (p.status === 'REFUNDED') {
        notificationsData.push({
          userId: b.customerId,
          type: payType,
          title: 'Refund Processed',
          body: `A refund of ₹${p.amount} for booking #${b.id} has been processed.`,
          isRead: Math.random() > 0.1,
          createdAt: p.updatedAt,
          data: { paymentId: p.id, bookingId: b.id }
        });
      }
    }
    
    // Reviews
    if (b.review) {
      notificationsData.push({
        userId: b.provider.userId,
        type: 'REVIEW_REQUEST',
        title: 'New Review Received!',
        body: `You received a ${b.review.rating}-star review for booking #${b.id}.`,
        isRead: Math.random() > 0.2,
        createdAt: b.review.createdAt,
        data: { reviewId: b.review.id, bookingId: b.id }
      });
    }
  }
  
  // 4. Provider Verification System Notifications
  const providers = users.filter(u => u.userRoles.some(r => r.role.name === 'PROVIDER'));
  for (const p of providers) {
    notificationsData.push({
      userId: p.id,
      type: 'SYSTEM',
      title: 'Profile Verification Complete',
      body: 'Your profile and documents have been approved. You can now accept bookings.',
      isRead: true,
      createdAt: new Date(p.createdAt.getTime() + 1000 * 60 * 60 * 24),
      data: { action: 'verification' }
    });
  }

  // Insert all
  await prisma.notification.createMany({ data: notificationsData });
  
  const total = await prisma.notification.count();
  console.log(`  ✓ ${total} Notifications generated across all users`);
}

// ─────────────────────────────────────────────────────────────────────────────
// STEP 17 — SUPPORT & DISPUTES SYSTEM
// ─────────────────────────────────────────────────────────────────────────────
async function seedSupportAndDisputes() {
  const bookings = await prisma.booking.findMany({ include: { provider: true } });
  const adminRole = await prisma.userRole.findFirst({ where: { role: { name: 'ADMIN' } } });
  const admin = await prisma.user.findFirst({ where: { id: adminRole.userId } });

  // Pick 8 random bookings
  const shuffled = bookings.sort(() => 0.5 - Math.random());
  const selectedBookings = shuffled.slice(0, 8);

  const disputeReasons = [
    { subject: "Provider arrived late", description: "The provider was over 2 hours late without any prior notice.", status: "RESOLVED", resolution: "Refunded 10% as apology." },
    { subject: "Incomplete work", description: "The service was not completed as described. Still leaking.", status: "OPEN" },
    { subject: "Poor service quality", description: "The cleaning was very superficial. Not satisfied.", status: "IN_REVIEW" },
    { subject: "Wrong service performed", description: "The technician fixed the wrong AC unit.", status: "RESOLVED", resolution: "Sent another technician to fix the correct unit free of charge." },
    { subject: "Payment issue", description: "I was charged twice for the same booking.", status: "CLOSED", resolution: "Duplicate charge refunded to source." },
    { subject: "Damage during service", description: "The provider scratched my floor while moving the fridge.", status: "IN_REVIEW" },
    { subject: "Provider did not arrive", description: "I waited all day but no one showed up.", status: "RESOLVED", resolution: "Full refund issued and provider warned." },
    { subject: "Unprofessional behavior", description: "The provider was very rude.", status: "OPEN" }
  ];

  let disputeCount = 0;
  let messageCount = 0;

  for (let i = 0; i < selectedBookings.length; i++) {
    const b = selectedBookings[i];
    const template = disputeReasons[i % disputeReasons.length];
    const customerId = b.customerId;

    const createdAt = new Date(b.createdAt.getTime() + 1000 * 60 * 60 * 48); // 2 days after booking

    const d = await prisma.dispute.create({
      data: {
        bookingId: b.id,
        raisedById: customerId,
        subject: template.subject,
        description: template.description,
        status: template.status,
        resolution: template.resolution || null,
        resolvedAt: (template.status === 'RESOLVED' || template.status === 'CLOSED') ? new Date(createdAt.getTime() + 1000 * 60 * 60 * 24 * 3) : null,
        createdAt: createdAt,
        updatedAt: createdAt
      }
    });
    disputeCount++;

    // Message 1: Customer
    await prisma.disputeMessage.create({
      data: {
        disputeId: d.id,
        senderId: customerId,
        message: `Hi, I want to report an issue: ${template.description}`,
        createdAt: new Date(createdAt.getTime() + 1000 * 60 * 5)
      }
    });
    messageCount++;

    // Message 2: Admin
    if (template.status !== 'OPEN') {
      await prisma.disputeMessage.create({
        data: {
          disputeId: d.id,
          senderId: admin.id,
          message: "We have received your dispute and are looking into it. Please allow us 24 hours.",
          createdAt: new Date(createdAt.getTime() + 1000 * 60 * 60 * 2)
        }
      });
      messageCount++;
    }

    // Message 3: Provider (Sometimes)
    if (template.status === 'IN_REVIEW' || template.status === 'RESOLVED') {
      await prisma.disputeMessage.create({
        data: {
          disputeId: d.id,
          senderId: b.provider.userId,
          message: "I apologize for the misunderstanding. I am willing to cooperate.",
          createdAt: new Date(createdAt.getTime() + 1000 * 60 * 60 * 12)
        }
      });
      messageCount++;
    }

    // Message 4: Resolution
    if (template.status === 'RESOLVED' || template.status === 'CLOSED') {
      await prisma.disputeMessage.create({
        data: {
          disputeId: d.id,
          senderId: admin.id,
          message: `This issue has been resolved. Note: ${template.resolution}`,
          createdAt: d.resolvedAt
        }
      });
      messageCount++;
    }
  }

  console.log(`  ✓ ${disputeCount} Disputes generated`);
  console.log(`  ✓ ${messageCount} Dispute Messages generated`);
}

// ─────────────────────────────────────────────────────────────────────────────
// Execute
// ─────────────────────────────────────────────────────────────────────────────
main()
  .catch((err) => {
    console.error('\n❌ Seed failed:', err.message);
    console.error(err.stack);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
